name: jtlc_front
description: JTLC Security Apps
publish_to: "none"
version: 1.0.2+2

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  animated_flip_counter: ^0.2.5
  cached_network_image: ^3.2.2
  camera: ^0.10.0+4
  cloud_firestore: ^4.0.4
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  encrypt: ^5.0.1
  extended_image: ^6.3.2
  fimber: ^0.6.6
  firebase_core: ^2.1.1
  firebase_dynamic_links: ^5.0.4
  firebase_messaging: ^14.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_feather_icons: ^2.0.0+1
  flutter_hooks: ^0.18.5+1
  flutter_image_compress: ^1.1.3
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_native_image: ^0.0.6
  flutter_native_splash: ^2.2.14
  flutter_screenutil: ^5.5.3+2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.1.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  go_router: ^5.0.5
  hooks_riverpod: ^2.1.1
  intl_phone_field: ^3.1.0
  jwt_decoder: ^2.0.1
  keyboard_dismisser: ^3.0.0
  logger: ^1.1.0
  mime: ^1.0.2
  mobile_scanner: ^2.0.0
  mockito: ^5.2.0
  path_provider: ^2.0.11
  pin_code_fields: ^7.4.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  rive: ^0.9.1
  riverpod_annotation: ^1.0.6
  sentry_flutter: ^6.9.0
  separated_row: ^2.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: any
  riverpod_generator: ^1.0.6

flutter_native_splash:
  background_image: "assets/images/splash_bg.png"
  branding_mode: bottom
  android_gravity: center_vertical
  fullscreen: true
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/avatar/
    - assets/icons/
