// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNE0sfEwvrj6jcQmXM_o6y-NNKoetez2g',
    appId: '1:1044322651897:android:3eeb927646f5712ede5c28',
    messagingSenderId: '1044322651897',
    projectId: 'my-japfa-prod',
    databaseURL: 'https://my-japfa-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-japfa-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Ns9XpsGtRF3m-Vnqq1qxEctrR14b7sU',
    appId: '1:1044322651897:ios:6405f723bec24541de5c28',
    messagingSenderId: '1044322651897',
    projectId: 'my-japfa-prod',
    databaseURL: 'https://my-japfa-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-japfa-prod.appspot.com',
    iosClientId: '1044322651897-4c221gv344t3h1rf8e8ifuuljam93rgh.apps.googleusercontent.com',
    iosBundleId: 'com.jtlc.jtlcQrScanner',
  );
}
